### PR TITLE
Update base URL.

### PR DESCRIPTION
**Pull request by tomusdrw**
Related #16 <- if this get's implemented the CI won't be able to provide incorrect hash nor we will use incorrect URL

### CODE REVIEW

**Comment by tomusdrw** [comment]
@5chdn @ddorgan can we be sure that there is no `http -> https` redirection? I think clients don't support neither redirections nor tls

**Review by ddorgan — APPROVED** [review]

**Comment by 5chdn** [comment]
it accepts both, http and https, I don't see why it should redirect though.

**Review by 5chdn — APPROVED** [review]

**Comment by tomusdrw** [comment]
> it accepts both, http and https, I don't see why it should redirect though.

I mentioned you guys to be sure we don't accidentally break this assumptions in the future (by redirecting http -> https or to a different URL).

**Comment by ddorgan** [comment]
It accepts http:

```
$ wget http://releases.parity.io/ethereum/v2.3.0/x86_64-unknown-linux-gnu/parity
--2019-01-16 15:56:07--  http://releases.parity.io/ethereum/v2.3.0/x86_64-unknown-linux-gnu/parity
Resolving releases.parity.io (releases.parity.io)... 143.204.214.12, 143.204.214.66, 143.204.214.96, ...
Connecting to releases.parity.io (releases.parity.io)|143.204.214.12|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 46430048 (44M) [binary/octet-stream]
Saving to: ‘parity’

parity                                    100%[=====================================================================================>]  44.28M  28.7MB/s    in 1.5s    

2019-01-16 15:56:09 (28.7 MB/s) - ‘parity’ saved [46430048/46430048]
```

**Pull request merged**
